### ISSUE TITLE
Add Animation & Window not closing correctly

### ISSUE THREAD

**Issue by 123marvin123** [kaunteya/InfoButton#2]
I think it would be nice if there is an animation when you click the InfoButton.

Besides that, there is a little bug when trying to open / close the window. If you don't move your cursor after you clicked, the next clicks won't be recognized anymore. I try to visualize this with this GIF-Image:
![Bug](https://www.dropbox.com/s/8ph7mktgtww52vw/Bug.gif?dl=1)

**Comment by kaunteya** [comment]
@123marvin123 I have released version `0.3.1`

I have added `@IBInspectable var animatePopover: Bool`, so that you can decide weather to animate the popover or not.

Also the bug of multiple clicks seems to have been solved.
